### ISSUE TITLE
Cannot find module '../protocol.json'

### ISSUE THREAD

**Issue by amcdnl** [BrowserSync/browser-sync-core#3]
When I run I get this:

```
[18:07:58] Error: Cannot find module '../protocol.json'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (C:\dev\swimlane\Web\node_modules\browser-sync-core\lib\protocol.js:2:13)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (C:\dev\swimlane\Web\node_modules\browser-sync-core\lib\sockets.js:4:15)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (C:\dev\swimlane\Web\node_modules\browser-sync-core\lib\browser-sync.js:15:15)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Gulp.<anonymous> (C:\dev\swimlane\Web\tasks\server.js:89:12)
  at module.exports (C:\dev\swimlane\Web\node_modules\orchestrator\lib\runTask.js:34:7)
  at Gulp.Orchestrator._runTask (C:\dev\swimlane\Web\node_modules\orchestrator\index.js:273:3)
  at Gulp.Orchestrator._runStep (C:\dev\swimlane\Web\node_modules\orchestrator\index.js:214:10)
  at Gulp.Orchestrator.start (C:\dev\swimlane\Web\node_modules\orchestrator\index.js:134:8)
  at C:\Users\austin\AppData\Roaming\nvm\v5.8.0\node_modules\gulp\bin\gulp.js:129:20
  at _combinedTickCallback (node.js:370:9)
  at process._tickCallback (node.js:401:11)
  at Function.Module.runMain (module.js:449:11)
  at startup (node.js:141:18)
  at node.js:933:3
```

**Comment by shakyShane** [comment]
Sorry this is still very much a WIP - I will add a note to the readme. Apologies for any wasted time :)

**Comment by amcdnl** [comment]
@shakyShane Thanks! I kinda thought that after I saw this but wasn't 100% sure.
